### ISSUE TITLE
Collection filters are applied to join table when classes have a N-N relationship

### ISSUE THREAD

**Issue by domurtag** [gpc/grails-hibernate-filter#9]
Given these domain classes

````groovy
class Problem {

    String name
    Integer status = 1

    static belongsTo = Condition

    static hasMany = [
            conditions: Condition
    ]

    static hibernateFilters = {
        statusFilter(condition: "status = 1")
        collectionFilter(condition: 'status = 1', collection: 'conditions')
    }
}

class Condition {

    String name
    Integer status = 1

    static hasMany = [
            problems: Problem
    ]

    static hibernateFilters = {
        statusFilter(condition: 'status = 1')
        collectionFilter(condition: 'status = 1', collection: 'problems')
    }
}
````

If all the filters are enabled, and this query is executed

````groovy
Problem.executeQuery("""
    SELECT  p
    FROM    ${Problem.simpleName} p
    JOIN    p.conditions""")
````

then the generated SQL is

````sql
        select
            problem0_.id as id1_4_,
            problem0_.version as version2_4_,
            problem0_.name as name3_4_,
            problem0_.status as status4_4_ 
        from
            problem problem0_ 
        inner join
            condition_problems conditions1_ 
                on problem0_.id=conditions1_.problem_id 
                and conditions1_.status = 1 
        inner join
            condition condition2_ 
                on conditions1_.condition_id=condition2_.id 
        where
            problem0_.status = 1
````

Notice in the SQL above, that the join table `condition_problems` is being filtered, rather than the associated collection (the `condition` table). The query naturally fails, because there is no `status` column in the join table.

This issue appears to be identical to [this Hibernate bug](https://hibernate.atlassian.net/browse/HHH-229) which was opened almost 10 years ago against an early version of Hibernate 3

Although it's claimed that the linked Hibernate issue is a duplicate, I can't find any trace of the original, or any evidence that the problem is fixed in the Hibernate 4 version this plugin is using.

I've pushed [a test](https://github.com/donalmurtagh/grails-hibernate-filter/commit/3143243c602cb1ca744ff6c6d31c8d9b182dd40c) to [this PR](https://github.com/burtbeckwith/grails-hibernate-filter/pull/7/) that demonstrates the issue.

**Comment by donalmurtagh** [comment]
I discovered that this issue occurs whenever the relationship between 2 domain classes results in the creation of a join table, e.g. the issue will also occur for a unidirectional 1-N relationship

**Comment by donalmurtagh** [comment]
I've added a commit to [my PR](https://github.com/donalmurtagh/grails-hibernate-filter/commit/847db176d637de0394f110509677c9ccfb78bc21) that includes a fix and regression tests for this issue. [This is the commit[(https://github.com/donalmurtagh/grails-hibernate-filter/commit/8d90540eba91f7af6f9fa692be03813223c8758c) that includes the fix.

The Hibernate Filters DSL now requires you to add an entry for filtered associations that are mapped via a join table, there are some examples in the tests, but basically you need to add a `joinTable: true` entry, e.g.
```
class Student {

    String name
    Integer status = 1

    static hasMany = [         
            loans: Loan,
            pens: Pen
    ]

    static hibernateFilters = {
        collegeFilter()
        collegeFilter(collection: 'loans')
        collegeFilter(collection: 'pens', joinTable: true)
    }
}
```

In the example above, `joinTable: true` is specified for the `pens` collection, but not the `loans` collection, because only the former is mapped via a join table.

**This information should be added to this plugin's docs** (which I have no access to)
